# Generated by Django 5.0 on 2024-02-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='state',
        ),
    ]
